"""make_tool_character_id_nullable_add_creator_id

Revision ID: 37d8b378e576
Revises: 0f4d3ab8be11
Create Date: 2026-03-19 00:34:44.132531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import GUID


# revision identifiers, used by Alembic.
revision: str = '37d8b378e576'
down_revision: Union[str, None] = '0f4d3ab8be11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', GUID(length=32), nullable=True))
        batch_op.alter_column('character_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.create_foreign_key('fk_tools_creator_id', 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tools_creator_id', type_='foreignkey')
        batch_op.alter_column('character_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
